### ISSUE TITLE
Ошибка при запуске контейнера dnsmasq - порт 53 занят

### ISSUE THREAD

**Issue by chatlamin** [alexanderfefelov/docker-backpack#2]
При запуске контейнера dnsmasq https://github.com/alexanderfefelov/docker-backpack/tree/master/dnsmasq с помощью файла ./run.sh получаю ошибку:

docker: Error response from daemon: driver failed programming external connectivity on endpoint backpack-dnsmasq (e6869872b033ec6adab9b41c70f7fa60521df1ccc79b65e8f89f859cf3c5b1b6): Error starting userland proxy: listen udp 0.0.0.0:53: bind: address already in use.

Проверяю действительно ли занят порт, который должен быть проброшен для контейнера:

sudo lsof -i -P -n | grep 53
systemd-r 671 systemd-resolve   12u  IPv4  21038      0t0  UDP 127.0.0.53:53
systemd-r 671 systemd-resolve   13u  IPv4  21039      0t0  TCP 127.0.0.53:53 (LISTEN)

Решение:
systemctl disable systemd-resolved.service
systemctl stop systemd-resolved
rm /etc/resolv.conf
echo nameserver 172.17.0.1 > /etc/resolv.conf 
echo nameserver 8.8.8.8 >> /etc/resolv.conf

Может указать это в README к контейнеру? https://github.com/alexanderfefelov/docker-backpack/blob/master/dnsmasq/README.md

**Comment by alexanderfefelov** [comment]
Я не могу даже предположить, какой из необходимых этому проекту [UDP](https://github.com/alexanderfefelov/docker-backpack/blob/master/doc/udp-port-inventory.csv)- или [TCP](https://github.com/alexanderfefelov/docker-backpack/blob/master/doc/tcp-port-inventory.csv)-портов может оказаться занятым на какой-то инсталляции и по какой причине это произошло. Поэтому не считаю возможным описывать здесь какие-то конкретные действия.
